# Generated by Django 3.2.25 on 2026-06-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='机房名称')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='容量(机位数)')),
                ('open_time', models.TimeField(default='08:00', verbose_name='开放时间')),
                ('close_time', models.TimeField(default='22:00', verbose_name='关闭时间')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '关闭'), ('maintenance', '维护中')], default='open', max_length=12, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='节次名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='机位编号')),
                ('status', models.CharField(choices=[('available', '可用'), ('maintenance', '维护中')], default='available', max_length=12, verbose_name='状态')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.room', verbose_name='所属机房')),
            ],
            options={
                'ordering': ['room', 'code'],
                'unique_together': {('room', 'code')},
            },
        ),
    ]
