# Generated by Django 3.2.25 on 2026-06-12 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], verbose_name='星期')),
                ('start_week', models.PositiveSmallIntegerField(default=1, verbose_name='起始周')),
                ('end_week', models.PositiveSmallIntegerField(default=18, verbose_name='结束周')),
                ('semester_start', models.DateField(verbose_name='学期开始日(第1周周一)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rooms.room', verbose_name='机房')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='教师')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.timeslot', verbose_name='节次')),
            ],
            options={
                'ordering': ['weekday', 'timeslot__order'],
            },
        ),
    ]
