# Generated by Django 4.2.16 on 2026-06-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTime',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=45, null=True)),
                ('start_time', models.CharField(blank=True, max_length=45, null=True)),
                ('end_time', models.CharField(blank=True, max_length=45, null=True)),
                ('uname', models.CharField(blank=True, max_length=8, null=True)),
                ('time_length', models.CharField(blank=True, max_length=45, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_time', models.CharField(blank=True, max_length=8, null=True)),
                ('daily_timecol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'daily_time',
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=8, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('uname', models.CharField(blank=True, max_length=45, null=True)),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=80, null=True)),
                ('finish', models.CharField(blank=True, max_length=8, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=4, null=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                'db_table': 'student_task',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(blank=True, max_length=8, null=True)),
                ('content', models.CharField(blank=True, max_length=80, null=True)),
                ('students', models.CharField(blank=True, max_length=80, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('finish', models.CharField(blank=True, max_length=8, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=4, null=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('date', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('time_day', models.IntegerField(blank=True, null=True)),
                ('time_week', models.IntegerField(blank=True, null=True)),
                ('time_month', models.IntegerField(blank=True, null=True)),
                ('apply', models.IntegerField(blank=True, null=True)),
                ('reason_a', models.CharField(blank=True, max_length=20, null=True)),
                ('leave', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, max_length=8, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=8, null=True)),
                ('room', models.CharField(blank=True, max_length=8, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=8, null=True)),
                ('birthday', models.CharField(blank=True, max_length=8, null=True)),
                ('photo', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
